theme: jekyll-theme-primer
title: Adam Ross
description: "GitHub profile site for Adam Ross."
image: "https://avatars.githubusercontent.com/u/14985050?v=4"
url: "https://r055a.github.io/R055A/"
profile_url: "https://github.com/R055A"
author:
    name: Adam Ross
plugins:
  - jekyll-seo-tag
